# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6786a0e1209f578b5a3cd5441182a8bafe09508f87456bb141ed81cdee7f7a074461c74f5f3121033730d5f3d7c55cb2c4ba44023c3037209f7f089bb936cd

test:
  secret_key_base: 0b9b9f6b01b771e72a7903add7b77ca7ca2eda4a9d7bee487e7e0fc235ae8b2e5ea13306d806e218b4cab4f1f23fe2fb2c17718d66ca5202afdba0c5482d02cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
